#!/usr/bin/env bash
# Configure my domain zone:
# www --> 156003-lb-01 52.23.177.96
# web-01 --> 156003-web-01 18.234.193.38
# web-02 --> 156003-web-02 54.196.32.245


subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
