#!/usr/bin/env bash
# configures nginx to run and listen to port 80
#There are many ways to kill a cat I think I have found one
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
